# ===== Oracle Database =====
spring.datasource.url=jdbc:oracle:thin:@localhost:1522/XE
spring.datasource.username=SYSTEM
spring.datasource.password=123456
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===== JPA / Hibernate =====
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desactiver le   et reduire les logs
spring.main.banner-mode=off
logging.level.org.hibernate.SQL=DEBUG

# ===== Server =====
server.port=8082